(function () {
  "use strict";

  /*
   * Lumen Fidei — Comparative Concepts Encyclopedia
   *
   * Editorial principle: each entry distinguishes (1) the shared Christian
   * question, (2) the internal logic of each tradition, and (3) the precise
   * point at which traditions diverge. Primary sources are privileged; free
   * scholarly/reference editions are used for orientation and historical context.
   */
  const concepts = [
    {
      id: "grace", name: "Grace", latin: "Gratia",
      short: "The free gift by which God calls, heals, sanctifies, and brings the creature into communion with Himself.",
      definition: "Grace is God's gratuitous action toward the creature: He gives what the creature cannot claim as a right, restores what sin has damaged, and raises human life toward communion with Himself. Christian traditions agree that salvation begins in divine initiative, but they differ in how grace relates to nature, freedom, justification, sacramental life, and theosis.",
      scope: "From Paul and the Fathers through Augustine's anti-Pelagian writings, medieval accounts of habitual and actual grace, the Reformation's sola gratia, and Eastern accounts of synergy and the divine energies, grace became one of Christianity's central questions: what must God do, and what can the human person do, for salvation?",
      treeUrl: "theological-tree.html?category=grace",
      traditions: {
        catholic: { thesis: "Grace is wholly gratuitous, precedes every salutary movement, heals fallen nature, and elevates the person into supernatural communion with God.", summary: "Catholic theology distinguishes actual grace, by which God moves a person toward particular acts, from sanctifying or habitual grace, a stable participation in divine life. Augustine's insistence on prevenient grace and Aquinas's analysis of grace and free cooperation are foundational. The Council of Trent rejects both Pelagian self-sufficiency and the claim that grace leaves the person merely externally covered. Grace initiates justification and continues as the source of sanctification and charity.", sources: [
          {title:"Augustine, On Grace and Free Will",url:"https://www.newadvent.org/fathers/1510.htm",note:"Primary source"},
          {title:"Aquinas, Summa Theologiae I-II, qq.109–114",url:"texts/summa.html?part=prima-sec&q=109&a=1",note:"Primary source"},
          {title:"Council of Trent, Decree on Justification",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Primary conciliar source"},
          {title:"Catholic Encyclopedia — Grace",url:"https://www.newadvent.org/cathen/06689x.htm",note:"Secondary reference"}
        ]},
        orthodox: { thesis: "Grace is God's living action and gift, by which human beings participate in divine life without becoming God by nature.", summary: "Eastern theology commonly describes salvation as synergy: divine initiative and sustaining action are primary, while the human person is genuinely called to respond. The goal is theosis, participation in God's life. The Palamite distinction between God's essence and energies gives later Orthodox theology a precise way to say that God Himself is truly encountered and communicated while His essence remains transcendent. Grace therefore belongs to a wider vision of healing, illumination, ascetic struggle, sacrament, and communion.", sources: [
          {title:"Athanasius, On the Incarnation",url:"https://www.newadvent.org/fathers/2802.htm",note:"Primary source"},
          {title:"Basil, On the Holy Spirit",url:"https://www.newadvent.org/fathers/3203.htm",note:"Primary source"},
          {title:"Gregory Palamas, The Triads",url:"https://www.gutenberg.org/ebooks/12914",note:"Free historical edition"},
          {title:"Vladimir Lossky, The Mystical Theology of the Eastern Church",url:"https://archive.org/details/mysticaltheology0000loss",note:"Secondary theology"}
        ]},
        protestant: { thesis: "Grace is God's free and unmerited favor in Christ; salvation cannot be grounded in human merit or natural ability.", summary: "Classical Protestant theology makes divine grace the decisive ground of salvation. Luther stresses the bondage of the fallen will and the promise of Christ received by faith. Reformed theology emphasizes God's sovereign initiative, effectual calling, and justification by faith apart from works. Lutheran and Reformed writers nevertheless insist that grace does not make holiness optional: living faith bears fruit, while works never become the ground on which the sinner earns acceptance before God.", sources: [
          {title:"Luther, The Bondage of the Will",url:"https://www.ccel.org/ccel/luther/bondage",note:"Primary source"},
          {title:"Augsburg Confession IV and VI",url:"https://bookofconcord.org/augsburg-confession/",note:"Lutheran confession"},
          {title:"Calvin, Institutes III",url:"https://www.ccel.org/ccel/calvin/institutes",note:"Reformed primary source"},
          {title:"Westminster Confession, chs. 9–13",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}
        ]}
      },
      clash: ["Is grace principally God's favor toward the sinner, an inward gift transforming the person, or both?", "Can fallen freedom make the first movement toward God, or does every salutary movement depend on prevenient/regenerating grace?", "Does cooperation with grace safeguard human freedom or risk obscuring grace's priority?", "How should sacramental grace, faith, and personal conversion be related?"],
      source:"Catechism of the Catholic Church, Grace and Justification",sourceUrl:"https://www.vatican.va/content/catechism/en/part_three/section_one/chapter_three/article_2/ii_grace.html"
    },
    {
      id:"justification", name:"Justification", latin:"Iustificatio",
      short:"God's gracious act of reconciling the sinner to Himself and making or declaring the sinner righteous.",
      definition:"Justification asks what happens when God receives the sinner as righteous in Christ. Catholic theology joins forgiveness to interior renewal; Lutheran theology stresses the forensic declaration received through faith; Reformed theology likewise distinguishes justification from sanctification while grounding both in union with Christ; Eastern theology generally places justification within the larger reality of healing, communion, and theosis.",
      scope:"The biblical vocabulary of righteousness, Paul's arguments in Romans and Galatians, Augustine, medieval scholastic theology, Luther and Melanchthon, the Council of Trent, and the Reformed confessions form the central historical debate.", treeUrl:"theological-tree.html?category=justification",
      traditions:{
        catholic:{thesis:"Justification is the remission of sins together with sanctification and renewal of the inner person by grace; it is initiated by grace and conferred ordinarily through Baptism.",summary:"The Council of Trent defines justification as more than a change in legal status: the sinner is forgiven and inwardly renewed by sanctifying grace. Faith is foundational, but the justified person is called to hope and charity, and growth in grace continues after initial justification. Catholic theology therefore distinguishes the gratuitous beginning of justification from the increase of righteousness in a life lived by grace. Christ's merits remain the sole ultimate ground of salvation; human cooperation is itself enabled by grace.",sources:[
          {title:"Council of Trent, Session VI",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Primary conciliar source"},{title:"Aquinas, Summa Theologiae I-II, q.113",url:"texts/summa.html?part=prima-sec&q=113&a=1",note:"Primary source"},{title:"Catechism §§1987–1995",url:"https://www.vatican.va/content/catechism/en/part_three/section_one/chapter_three/article_2/grace_and_justification.html",note:"Contemporary Catholic synthesis"},{title:"Augustine, On the Spirit and the Letter",url:"https://www.newadvent.org/fathers/1502.htm",note:"Patristic source"}]},
        orthodox:{thesis:"Righteousness is received as life in Christ; forgiveness, healing, sanctification, and deification belong together rather than forming competing mechanisms.",summary:"Eastern Christianity retains biblical and liturgical language of justification but does not ordinarily make a sharp forensic-versus-transformative opposition the organizing principle of salvation. The sinner is forgiven, illumined, healed, incorporated into Christ, and called to participate in divine life. Faith is inseparable from baptismal and eucharistic incorporation and from the ascetic life of repentance. Theosis is not an optional sequel to justification but the positive end toward which salvation moves.",sources:[
          {title:"John Chrysostom, Homilies on Romans",url:"https://www.newadvent.org/fathers/2102.htm",note:"Primary commentary"},{title:"Athanasius, On the Incarnation",url:"https://www.newadvent.org/fathers/2802.htm",note:"Patristic soteriology"},{title:"Nicholas Cabasilas, The Life in Christ",url:"https://archive.org/details/lifeinchrist0000caba",note:"Secondary/free edition"}]},
        protestant:{thesis:"The sinner is accepted as righteous for Christ's sake through faith; Christ's righteousness, not the sinner's works, is the ground of acceptance.",summary:"Lutheran and Reformed theology both insist that justification cannot be earned. The Augsburg Confession says that sinners are freely justified for Christ's sake through faith, while Calvin describes justification as God's gracious acceptance of the sinner, grounded in Christ's righteousness and received by faith. Good works necessarily follow living faith, but they do not become the basis of the verdict that reconciles the sinner to God. Protestant traditions therefore sharply distinguish justification from sanctification while refusing to separate them in the Christian life.",sources:[
          {title:"Augsburg Confession IV",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_iv/",note:"Primary Lutheran confession"},{title:"Augsburg Confession VI and XX",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_xx/",note:"Faith and works"},{title:"Calvin, Institutes III.11",url:"https://www.ccel.org/ccel/calvin/institutes.v.xii.html",note:"Primary Reformed source"},{title:"Westminster Confession XI",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },
      clash:["Imputed righteousness and forensic declaration versus inwardly infused righteousness and renewal.","Faith alone as the sole instrument versus faith formed and perfected by charity.","Whether works can increase the believer's righteousness before God or only manifest the fruit of grace.","How tightly should justification be distinguished from sanctification?"],source:"Catechism of the Catholic Church, §§1987–1995",sourceUrl:"https://www.vatican.va/content/catechism/en/part_three/section_one/chapter_three/article_2/grace_and_justification.html"
    },
    {
      id:"eucharist",name:"Eucharist",latin:"Eucharistia",short:"The sacramental meal in which Christians receive communion in Christ's Body and Blood.",
      definition:"The Eucharist stands at the center of Christian worship because the New Testament joins the Lord's Supper to Christ's command, covenant, sacrifice, communion, and remembrance. All classical traditions affirm its centrality, but they disagree over the mode of Christ's presence, the nature of the sacrifice, and the relationship between sign and reality.",scope:"The Last Supper narratives, John 6, 1 Corinthians 10–11, Ignatius, Justin Martyr, Cyril of Jerusalem, medieval Eucharistic theology, Trent, Luther, Calvin, and Reformed confessions provide the principal sources.",treeUrl:"theological-tree.html?category=eucharist",
      traditions:{
        catholic:{thesis:"Christ is truly, really, and substantially present; the bread and wine become His Body and Blood, and the Eucharist makes sacramentally present the one sacrifice of Christ.",summary:"Catholic doctrine calls the change transubstantiation: the substance of bread and wine is changed while the sensible appearances remain. The Eucharist is both sacrament and sacrifice, not a new sacrifice competing with Calvary but the sacramental presence of Christ's one offering. Communion unites believers to Christ and builds the Church. The Council of Trent therefore rejects both a merely symbolic account and the idea that the Mass repeats Christ's sacrifice as though Calvary were insufficient.",sources:[{title:"Ignatius of Antioch, Letter to the Smyrnaeans",url:"https://www.newadvent.org/fathers/0109.htm",note:"Early witness to Real Presence"},{title:"Cyril of Jerusalem, Mystagogical Catecheses",url:"https://www.newadvent.org/fathers/3101.htm",note:"Primary patristic source"},{title:"Council of Trent, Eucharist",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Historical reference"},{title:"Aquinas, Summa III, qq.73–83",url:"texts/summa.html?part=tertia&q=73&a=1",note:"Scholastic synthesis"}]},
        orthodox:{thesis:"The Eucharist is truly the Body and Blood of Christ, received as participation in His life and offered in thanksgiving within the Church's liturgy.",summary:"Orthodox Christianity rejects reducing the Eucharist to a bare memorial. The liturgy speaks of real participation, sacrifice, communion, and transformation, while generally resisting attempts to define the mystery through a single Western scholastic mechanism. The Eucharist is the center of ecclesial life: in it the Church gives thanks, receives Christ, and is gathered into the Kingdom. Eucharistic realism therefore belongs to the wider sacramental and liturgical vision of theosis.",sources:[{title:"Ignatius of Antioch, Letter to the Smyrnaeans",url:"https://www.newadvent.org/fathers/0109.htm",note:"Primary source"},{title:"John Chrysostom, Homilies on Matthew",url:"https://www.newadvent.org/fathers/2001.htm",note:"Eucharistic preaching"},{title:"Cyril of Jerusalem, Catecheses",url:"https://www.newadvent.org/fathers/3101.htm",note:"Primary source"}]},
        protestant:{thesis:"Lutherans confess Christ's true sacramental presence; Reformed churches confess real spiritual communion with Christ; memorialist traditions interpret the Supper primarily as remembrance and proclamation.",summary:"The Reformation did not produce one Eucharistic doctrine. Lutherans retain strong sacramental realism and confess Christ's true presence with the consecrated elements. Reformed theology rejects both a merely mental memorial and a local physical enclosure of Christ, teaching that believers truly feed on Christ spiritually through the Holy Spirit and faith. Zwinglian and later free-church traditions place greater emphasis on remembrance, proclamation, and covenantal obedience. Classical Protestants generally reject the Mass as a propitiatory sacrifice added to Calvary.",sources:[{title:"Augsburg Confession X",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_x/",note:"Lutheran confession"},{title:"Calvin, Institutes IV.17",url:"https://www.ccel.org/ccel/calvin/institutes.iv.xvii.html",note:"Reformed primary source"},{title:"Second Helvetic Confession XXI",url:"https://www.ccel.org/creeds/helvetic.htm",note:"Reformed confession"}]}
      },
      clash:["Transubstantiation, sacramental union, spiritual presence, and memorial interpretation.","The Eucharist as sacramental sacrifice versus a memorial or thanksgiving that does not itself offer Christ.","Whether Christ's Body is objectively present apart from the communicant's faith.","The relation between Eucharist, priesthood, apostolic succession, and ecclesial unity."],source:"Ignatius of Antioch, Letter to the Smyrnaeans",sourceUrl:"https://www.newadvent.org/fathers/0109.htm"
    },
    {
      id:"trinity",name:"Trinity",latin:"Trinitas",short:"The one God eternally existing as Father, Son, and Holy Spirit.",definition:"The Trinity is not belief in three gods but the confession that the one divine being is eternally possessed by three distinct divine Persons. Father, Son, and Spirit are not three parts of God; each is fully God, while the divine nature is one. Christian theology therefore has to preserve both divine unity and personal distinction.",scope:"The baptismal and doxological language of the New Testament, Nicaea and Constantinople, the Cappadocians, Augustine, Aquinas, and the classical creeds form the common foundation. The Filioque becomes the major East–West controversy.",treeUrl:"theological-tree.html?category=trinity",
      traditions:{
        catholic:{thesis:"One God in three Persons; the Spirit proceeds eternally from the Father and the Son as from one principle.",summary:"Latin theology follows the Nicene faith and develops the language of substance, person, relation, and procession. Augustine's De Trinitate searches for analogies in memory, understanding, and will while insisting that no analogy comprehends God. Aquinas distinguishes the processions of the Word and Love and explains the divine relations. The Western Filioque is understood as affirming the Spirit's relation to both Father and Son without establishing two independent sources of the Spirit's procession.",sources:[{title:"Augustine, De Trinitate",url:"https://www.newadvent.org/fathers/1301.htm",note:"Primary source"},{title:"Aquinas, Summa I, qq.27–43",url:"texts/summa.html?part=prima&q=27&a=1",note:"Primary source"},{title:"Athanasian Creed",url:"https://www.newadvent.org/cathen/02033b.htm",note:"Creedal source"}]},
        orthodox:{thesis:"One God, the Father as the personal source or monarchy; the Son eternally begotten of the Father and the Spirit eternally proceeding from the Father.",summary:"The Cappadocian Fathers articulate one ousia and three hypostases. Eastern theology places special emphasis on the Father's monarchy as the personal source of the Son and Spirit. The Orthodox reject the Filioque as a unilateral alteration of the Creed and object to formulations that seem to introduce two principles in the Spirit's procession. The distinction between God's unknowable essence and His genuinely communicable energies later becomes important in articulating communion without comprehension.",sources:[{title:"Basil, On the Holy Spirit",url:"https://www.newadvent.org/fathers/3203.htm",note:"Primary source"},{title:"Gregory Nazianzen, Theological Orations",url:"https://www.newadvent.org/fathers/3102.htm",note:"Primary source"},{title:"John of Damascus, Exact Exposition",url:"https://www.newadvent.org/fathers/3304.htm",note:"Primary source"}]},
        protestant:{thesis:"The Reformation retains Nicene and Trinitarian Christianity while generally inheriting the Western Filioque tradition.",summary:"Lutheran and Reformed confessions stand within the Nicene catholic tradition and reject anti-Trinitarian interpretations. Calvin's treatment stresses that the names Father, Son, and Spirit designate real personal distinctions without dividing the divine essence. Protestant theology differs internally over theological method, but classical confessions do not revise the basic Nicene grammar: one God, three Persons, eternal relations, and the full divinity of the Son and Spirit.",sources:[{title:"Augsburg Confession I",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_i/",note:"Lutheran confession"},{title:"Calvin, Institutes I.13",url:"https://www.ccel.org/ccel/calvin/institutes.i.xiii.html",note:"Primary Reformed source"},{title:"Westminster Confession II",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["The Filioque and the question of the Spirit's eternal procession.","How should the Father's monarchy be understood without subordinating the Son or Spirit?","How far may psychological or created analogies be used to illuminate the Trinity without reducing the mystery?","How can divine unity be confessed without modalism, and personal distinction without tritheism?"],source:"Nicene and Constantinopolitan Creed — Catholic Encyclopedia",sourceUrl:"https://www.newadvent.org/cathen/11049a.htm"
    },
    {
      id:"atonement",name:"Atonement",latin:"Redemptio",short:"The saving work of Christ by which sin, death, and alienation are overcome.",definition:"Atonement names the mystery by which Christ's life, death, resurrection, and exaltation reconcile humanity to God. Scripture uses several complementary images: sacrifice, Passover, ransom, victory, representation, reconciliation, healing, and the bearing of sin. The traditions differ less over whether Christ saves through His Cross than over which biblical images should govern the explanation.",scope:"Irenaeus's recapitulation, Athanasius's victory over death, Anselm's satisfaction, Aquinas's synthesis, Luther's theology of the Cross, Calvin's substitutionary account, and modern retrievals provide the major trajectories.",treeUrl:"theological-tree.html?category=atonement",
      traditions:{
        catholic:{thesis:"Christ's Passion is the unique sacrificial offering that satisfies for sin, merits grace, defeats death, and reconciles humanity to God.",summary:"Catholic theology does not reduce the Cross to a single theory. Anselm's satisfaction, patristic victory, sacrifice, merit, and substitution are integrated in a larger Christological account. Aquinas emphasizes Christ's Passion as sacrifice, satisfaction, merit, redemption, and efficient cause of salvation. The Mass sacramentally makes present the one sacrifice rather than adding another sacrifice to Calvary.",sources:[{title:"Anselm, Cur Deus Homo",url:"https://www.ccel.org/ccel/anselm/basic_works",note:"Primary source"},{title:"Aquinas, Summa III, qq.46–49",url:"texts/summa.html?part=tertia&q=48&a=1",note:"Primary source"},{title:"Irenaeus, Against Heresies V",url:"https://www.newadvent.org/fathers/0103.htm",note:"Patristic recapitulation"}]},
        orthodox:{thesis:"Christ enters death, destroys its power, heals human nature, and opens participation in divine life; the Cross cannot be separated from the Incarnation and Resurrection.",summary:"Eastern Christianity commonly places Christus Victor, recapitulation, healing, and deification at the center of its soteriology. The problem is not merely a legal debt but humanity's captivity to corruption and death. Christ assumes human nature, restores it, passes through death, and raises it. Juridical language is present in Scripture and liturgy, but the whole Paschal mystery is treated as the saving event rather than a transaction isolated from the Incarnation and Resurrection.",sources:[{title:"Athanasius, On the Incarnation",url:"https://www.newadvent.org/fathers/2802.htm",note:"Primary source"},{title:"Irenaeus, Against Heresies",url:"https://www.newadvent.org/fathers/0103.htm",note:"Recapitulation"},{title:"John of Damascus, Exact Exposition",url:"https://www.newadvent.org/fathers/3304.htm",note:"Primary source"}]},
        protestant:{thesis:"Christ's death is substitutionary and sufficient for salvation; classical Protestantism strongly emphasizes the bearing of sin and judgment in the sinner's place.",summary:"Lutheran theology combines Christ's substitution with victory, the theology of the Cross, and Christ's descent and resurrection. Reformed theology gives a particularly systematic form to penal substitution: Christ bears the penalty due to sinners and satisfies divine justice, while His righteousness is credited to believers. Protestant traditions continue to debate the extent of the atonement and the relation of penal substitution to Christus Victor, moral transformation, and covenantal representation.",sources:[{title:"Luther, Heidelberg Disputation",url:"https://www.ccel.org/ccel/luther/works",note:"Primary corpus"},{title:"Calvin, Institutes II.16–17",url:"https://www.ccel.org/ccel/calvin/institutes.ii.xvi.html",note:"Primary source"},{title:"Westminster Confession VIII",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["Satisfaction and penal substitution versus therapeutic and victorious models.","Is divine justice best described as punishment, satisfaction, restoration, or victory over death?","How should the Cross be related to the Incarnation and Resurrection?","Does the atonement objectively reconcile humanity to God, or must its benefits be personally appropriated through faith and sacramental life?"],source:"Athanasius, On the Incarnation",sourceUrl:"https://www.newadvent.org/fathers/2802.htm"
    },
    {
      id:"church",name:"Church",latin:"Ecclesia",short:"The people of God gathered into Christ's Body and sent into the world.",definition:"The Church is not merely an association of individuals who share beliefs. In the New Testament it is the Body of Christ, temple of the Spirit, people of God, bride, and visible assembly. The great ecclesiological question is how the Church's visible structure, sacramental life, apostolic ministry, holiness, and unity relate to the invisible work of grace.",scope:"The New Testament, Ignatius of Antioch, Cyprian, Augustine, medieval ecclesiology, the Reformation, Vatican II, and modern Orthodox and Protestant ecclesiology provide the principal streams.",treeUrl:"theological-tree.html?category=church",
      traditions:{
        catholic:{thesis:"The Church is the visible, sacramental, apostolic communion constituted by Christ and sustained by the Spirit, with bishops in communion with the Bishop of Rome serving its unity.",summary:"Catholic ecclesiology joins the Church's mystical identity as Christ's Body to a concrete visible communion. Scripture, Tradition, sacramental life, apostolic succession, and hierarchical ministry belong together. The Church is holy while containing sinners who are called to conversion. The bishop of Rome has a distinctive universal primacy rooted, in Catholic interpretation, in Peter and the apostolic college.",sources:[{title:"Ignatius of Antioch, Smyrnaeans",url:"https://www.newadvent.org/fathers/0109.htm",note:"Early ecclesiology"},{title:"Cyprian, On the Unity of the Church",url:"https://www.newadvent.org/fathers/050701.htm",note:"Primary source"},{title:"Vatican II, Lumen Gentium",url:"https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19641121_lumen-gentium_en.html",note:"Magisterial source"}]},
        orthodox:{thesis:"The Church is the Eucharistic and conciliar Body of Christ, preserving the apostolic faith through bishops, sacraments, liturgy, and communion.",summary:"Orthodox ecclesiology emphasizes the local Church gathered around its bishop in the Eucharist and the communion of local Churches in conciliarity. Apostolic succession and sacramental continuity are essential, but no single bishop is understood as possessing universal jurisdiction analogous to the Catholic papacy. The Church is the place where the apostolic faith is lived, prayed, sacramentally embodied, and handed down through the Fathers and councils.",sources:[{title:"Ignatius of Antioch, Letter to the Smyrnaeans",url:"https://www.newadvent.org/fathers/0109.htm",note:"Primary source"},{title:"Cyprian, On the Unity of the Church",url:"https://www.newadvent.org/fathers/050701.htm",note:"Primary source"},{title:"Nicholas Afanasiev, The Church of the Holy Spirit",url:"https://archive.org/details/churchofholyspir0000afan",note:"Secondary theology"}]},
        protestant:{thesis:"The Church is constituted by the Word and sacraments and is recognized wherever the Gospel is rightly preached and the sacraments rightly administered.",summary:"Lutheran and Reformed ecclesiology rejects the claim that the Church's essence depends upon communion with a single universal bishop. The Augsburg Confession defines the Church as the assembly in which the Gospel is taught purely and the sacraments administered according to the Gospel. Reformed theology similarly distinguishes the visible and invisible dimensions of the Church while insisting that the true Church must be identifiable through Word, sacrament, and discipline. Anglican, Baptist, Methodist, and other Protestant traditions modify these principles in different ways.",sources:[{title:"Augsburg Confession VII",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_vii/",note:"Lutheran confession"},{title:"Calvin, Institutes IV.1–2",url:"https://www.ccel.org/ccel/calvin/institutes.iv.i.html",note:"Reformed primary source"},{title:"Westminster Confession XXV",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["Visible sacramental communion versus a broader definition centered on Word and faith.","Universal papal jurisdiction versus conciliar communion of autocephalous Churches.","Apostolic succession as constitutive of the Church versus succession primarily understood through fidelity to apostolic teaching.","How should the Church's holiness be understood when its members remain sinners?"],source:"Ignatius of Antioch, Letter to the Smyrnaeans",sourceUrl:"https://www.newadvent.org/fathers/0109.htm"
    },
    {
      id:"free-will",name:"Free Will",latin:"Liberum Arbitrium",short:"Human freedom and responsibility under the conditions of creation, sin, grace, and divine providence.",definition:"Christian theology must hold together two claims that can appear difficult to reconcile: God is sovereign and salvation is by grace, yet human beings are responsible agents who are commanded to repent, believe, love, and obey. The traditions disagree over the condition of freedom after the Fall and over the precise manner in which grace and freedom cooperate.",scope:"Paul, Augustine, Pelagius, Aquinas, Luther, Calvin, Wesley, and the Eastern Fathers provide the major historical debate.",treeUrl:"theological-tree.html?category=free-will",
      traditions:{
        catholic:{thesis:"Human free will is wounded, not destroyed, by original sin; grace precedes and enables every salutary act while freedom genuinely cooperates.",summary:"Augustine's mature anti-Pelagian theology rejects the idea that fallen humanity can turn to God by unaided nature. Aquinas likewise teaches that grace is necessary for every act ordered to supernatural beatitude. Yet Catholic theology denies that grace turns the will into an inert instrument. The Council of Trent explicitly teaches that the sinner can reject grace and that human cooperation, itself enabled by grace, is real.",sources:[{title:"Augustine, Grace and Free Will",url:"https://www.newadvent.org/fathers/1510.htm",note:"Primary source"},{title:"Aquinas, ST I-II q.109",url:"texts/summa.html?part=prima-sec&q=109&a=1",note:"Primary source"},{title:"Council of Trent, Session VI",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Primary source"}]},
        orthodox:{thesis:"Human freedom remains real after the Fall, though weakened by corruption and death; salvation is synergy with divine grace.",summary:"Eastern anthropology generally avoids the Augustinian debate in the later Western forms of total inability and irresistible grace. Humanity is wounded and enslaved to passions and death, but the image of God is not annihilated. God's initiative remains indispensable, yet the ascetic and liturgical tradition repeatedly calls the person to a free response: repentance, faith, prayer, fasting, and love. Synergy means cooperation with grace, never autonomous self-salvation.",sources:[{title:"John Cassian, Conferences",url:"https://www.newadvent.org/fathers/3501.htm",note:"Primary ascetical source"},{title:"John Chrysostom, Homilies on Romans",url:"https://www.newadvent.org/fathers/2102.htm",note:"Primary source"},{title:"Maximus the Confessor, Selected Works",url:"https://archive.org/details/maximusconfessor0000maxi",note:"Secondary/free edition"}]},
        protestant:{thesis:"Classical Protestantism denies that fallen humanity can initiate saving faith by natural power; the regenerate person nevertheless acts freely and necessarily bears fruit.",summary:"Luther's Bondage of the Will and Calvin's doctrine of effectual calling place strong emphasis on the incapacity of fallen humanity to produce saving faith unaided. Lutheran theology speaks of bondage in conversion while affirming genuine responsibility; Reformed theology distinguishes moral inability from coercion: sinners choose willingly according to their fallen desires, and regenerating grace changes those desires. Wesleyan and Arminian Protestants later develop a different account through prevenient grace, which restores a genuine capacity to respond.",sources:[{title:"Luther, Bondage of the Will",url:"https://www.ccel.org/ccel/luther/bondage",note:"Primary source"},{title:"Calvin, Institutes II.2–5",url:"https://www.ccel.org/ccel/calvin/institutes.ii.ii.html",note:"Primary source"},{title:"Wesley, On Working Out Our Own Salvation",url:"https://ccel.org/ccel/wesley/sermons/85",note:"Later Protestant development"}]}
      },clash:["Wounded freedom versus total inability in fallen humanity.","Prevenient grace and resistibility versus effectual or irresistible grace.","How can divine providence be exhaustive without making human action meaningless?","Does foreknowledge determine the act, or merely know what the free creature will do?"],source:"Augustine, Grace and Free Will",sourceUrl:"https://www.newadvent.org/fathers/1510.htm"
    },
    {
      id:"original-sin",name:"Original Sin",latin:"Peccatum Originale",short:"The inherited condition of fallen humanity and its alienation from God.",definition:"Original sin is Christianity's account of the universal human condition: humanity is not born morally and spiritually neutral but enters a world already marked by Adam's fall, disordered desire, corruption, and death. Traditions differ over whether Adam's guilt itself is transmitted, how freedom is affected, and how baptism addresses the condition.",scope:"Genesis 3, Romans 5, Augustine's anti-Pelagian writings, Eastern patristic anthropology, Aquinas, Luther, Calvin, and the Council of Trent form the major trajectories.",treeUrl:"theological-tree.html?category=original-sin",
      traditions:{
        catholic:{thesis:"Adam's original sin is transmitted as a deprivation of original holiness and a wounded condition, not as a personal act committed by each descendant.",summary:"Catholic doctrine distinguishes personal sin from original sin. The latter is inherited as a fallen condition: humanity lacks the original holiness intended for communion with God and experiences ignorance, suffering, concupiscence, and death. Baptism removes original sin and restores sanctifying grace, though the inclination to sin remains as a field for spiritual struggle. Mary receives a unique preservation from original sin in the Immaculate Conception.",sources:[{title:"Augustine, On Nature and Grace",url:"https://www.newadvent.org/fathers/1503.htm",note:"Primary source"},{title:"Aquinas, ST I-II qq.81–85",url:"texts/summa.html?part=prima-sec&q=81&a=1",note:"Primary source"},{title:"Council of Trent, Decree on Original Sin",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Conciliar context"},{title:"Catechism §§385–421",url:"https://www.vatican.va/archive/ENG0015/__P1C.HTM",note:"Secondary synthesis"}]},
        orthodox:{thesis:"Humanity inherits corruption and death from Adam, not personal culpability for Adam's individual act in the same Western sense.",summary:"Orthodox writers commonly prefer 'ancestral sin' when explaining the inherited condition. Adam's fall introduces corruption, mortality, disordered desire, and alienation into human existence. The human person is not treated as personally guilty for Adam's act before committing any personal sin, yet all share the consequences of the Fall and therefore need Christ's healing. Baptism incorporates the person into Christ's death and resurrection and begins the restoration of human nature.",sources:[{title:"John Chrysostom, Homilies on Romans",url:"https://www.newadvent.org/fathers/2102.htm",note:"Primary source"},{title:"Gregory of Nyssa, On the Making of Man",url:"https://www.newadvent.org/fathers/2914.htm",note:"Primary source"},{title:"John of Damascus, Exact Exposition",url:"https://www.newadvent.org/fathers/3304.htm",note:"Primary source"}]},
        protestant:{thesis:"Adam's fall leaves humanity corrupted and unable to attain righteousness by natural power; classical Reformed theology also affirms inherited guilt and imputed Adamic condemnation.",summary:"Lutheran and Reformed theology makes original sin a radical account of human inability. The Augsburg Confession describes humanity as born without fear of God and with concupiscence; Reformed confessions speak of Adam's guilt being imputed and of humanity's corruption extending to every faculty. This doctrine grounds the necessity of grace and the radical sufficiency of Christ's righteousness. Baptism and regeneration are understood differently across Protestant traditions.",sources:[{title:"Augsburg Confession II",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_ii/",note:"Lutheran confession"},{title:"Calvin, Institutes II.1",url:"https://www.ccel.org/ccel/calvin/institutes.ii.i.html",note:"Primary source"},{title:"Westminster Confession VI",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["Inherited guilt versus inherited corruption/death.","Whether concupiscence after Baptism is itself sin or an inclination that is not personal sin until consent.","How extensive is the damage to reason and will?","What exactly does baptism remove: guilt, corruption, both, or chiefly the dominion of sin?"],source:"Augustine, On Nature and Grace",sourceUrl:"https://www.newadvent.org/fathers/1503.htm"
    },
    {
      id:"baptism",name:"Baptism",latin:"Baptismus",short:"The sacramental initiation into Christ through water and the Triune name.",definition:"Baptism is the Christian initiation into Christ through water and the Triune name. It is associated in the New Testament with repentance, forgiveness, regeneration, union with Christ’s death and resurrection, incorporation into the Church, and the gift of the Spirit. The traditions differ over the relation of baptism to justification, regeneration, faith, covenant, and the timing of baptism.",scope:"The baptismal commands of Matthew 28, Romans 6, Acts, the Didache, Cyril of Jerusalem, Augustine, Aquinas, Luther, Calvin, Trent, and the Reformed confessions form the principal historical conversation.",treeUrl:"theological-tree.html?category=baptism",
      traditions:{
        catholic:{thesis:"Baptism is the sacrament of regeneration and forgiveness that incorporates the person into Christ and His Church.",summary:"Catholic theology teaches that baptism removes original and personal sin, gives sanctifying grace, incorporates the baptized into Christ and the Church, and leaves an indelible sacramental character. Infant baptism is defended because grace is gift rather than a reward for mature intellectual decision.",sources:[{title:"Cyril of Jerusalem, Catechetical Lectures",url:"https://www.newadvent.org/fathers/3101.htm",note:"Primary source"},{title:"Aquinas, Summa III, qq.66–69",url:"texts/summa.html?part=tertia&q=66&a=1",note:"Primary source"},{title:"Catechism §§1210–1284",url:"https://www.vatican.va/content/catechism/en/part_two/section_two/chapter_one/article_1.html",note:"Secondary synthesis"}]},
        orthodox:{thesis:"Baptism is death and rebirth in Christ, ordinarily joined immediately to chrismation and Eucharistic communion.",summary:"Orthodox baptism is deeply Paschal: immersion signifies burial and rising with Christ. The newly baptized is incorporated into the Church and normally receives chrismation and Eucharist as part of one initiation. Infant baptism is normal because salvation is incorporation into Christ and His Church.",sources:[{title:"Cyril of Jerusalem, Catecheses",url:"https://www.newadvent.org/fathers/3101.htm",note:"Primary source"},{title:"Orthodox Church in America, Baptism",url:"https://www.oca.org/orthodoxy/the-orthodox-faith/doctrine-scripture/the-symbol-of-faith/sacraments",note:"Secondary traditional synthesis"}]},
        protestant:{thesis:"Lutherans confess baptism as a means of grace; Reformed theology calls it a covenant sign and seal, while Baptist traditions generally practice believer’s baptism.",summary:"Classical Protestants do not share one baptismal theology. Lutherans teach that God gives forgiveness and new birth through baptism. Reformed churches retain infant baptism but distinguish the outward sign from the Spirit’s inward work. Baptist traditions identify baptism with conscious profession and discipleship rather than infant covenant membership.",sources:[{title:"Augsburg Confession IX",url:"https://bookofconcord.org/augsburg-confession/chief_articles/article_ix/",note:"Lutheran confession"},{title:"Westminster Confession XXVIII",url:"https://wts.edu/wcf",note:"Reformed confession"},{title:"Luther, Small Catechism",url:"https://bookofconcord.org/small-catechism/",note:"Primary confession"}]}} ,clash:["Sacramental regeneration versus baptism as sign and seal.","Infant baptism versus believer’s baptism.","Whether baptismal grace is tied to the moment of administration.","The relation between baptism, faith, and covenant membership."],source:"Cyril of Jerusalem, Catechetical Lectures",sourceUrl:"https://www.newadvent.org/fathers/3101.htm"
    },
    {
      id:"penance",name:"Penance",latin:"Paenitentia",short:"Repentance and reconciliation after baptism through confession, absolution, and renewed life.",definition:"Penance is the Church’s response to post-baptismal sin: repentance, confession, forgiveness, reconciliation, and renewed life. Catholicism treats sacramental confession as a distinct sacrament; Orthodoxy practices sacramental confession and absolution within spiritual fatherhood; Lutheranism retains private confession and absolution; Reformed traditions emphasize repentance, discipline, and pastoral proclamation without a sacrament of penance in the Catholic sense.",scope:"Christ’s teaching on the keys, John 20, early penitential discipline, Tertullian, Cyprian, Chrysostom, medieval confession, Luther, Calvin, Trent, and Protestant confessions form the major historical trajectory.",treeUrl:"theological-tree.html?category=penance",
      traditions:{
        catholic:{thesis:"Penance is the sacrament by which the baptized are reconciled to God and the Church after sin through contrition, confession, absolution, and satisfaction.",summary:"Catholic theology understands Christ’s gift of the keys as establishing a ministry in which the Church forgives sins in His name. The priest acts sacramentally, absolution restores sanctifying grace when lost through mortal sin, and penance orders the forgiven person toward healing and restitution.",sources:[{title:"Council of Trent, Session XIV",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Primary council"},{title:"Aquinas, Summa III, qq.84–90",url:"texts/summa.html?part=tertia&q=84&a=1",note:"Primary source"},{title:"Catechism §§1422–1498",url:"https://www.vatican.va/content/catechism/en/part_two/section_two/chapter_two/article_4.html",note:"Secondary synthesis"}]},
        orthodox:{thesis:"Confession and absolution are sacramental mysteries of repentance in which the sinner is reconciled to God within the Church.",summary:"Orthodox confession is normally made before a priest who serves as witness, pastor, and spiritual guide. The emphasis is often therapeutic rather than merely juridical: sin wounds communion, repentance restores communion, and absolution is God’s mercy ministered through the Church.",sources:[{title:"John Chrysostom, On the Priesthood",url:"https://www.newadvent.org/fathers/1922.htm",note:"Primary source"},{title:"Orthodox Church in America, Questions on the Sacraments",url:"https://www.oca.org/questions/sevensacraments/questions-on-the-sacraments",note:"Secondary traditional synthesis"}]},
        protestant:{thesis:"Lutherans retain private confession and absolution as a precious ministry of the Gospel; Reformed churches emphasize repentance, discipline, and the preached declaration of forgiveness.",summary:"Lutheran theology retains objective absolution while rejecting the medieval system of sacramental satisfaction as necessary to justification. Reformed churches ordinarily do not treat penance as a sacrament, but retain corporate confession, pastoral forgiveness, and church discipline as means of restoring believers to faithful life.",sources:[{title:"Luther, Small Catechism: Confession",url:"https://bookofconcord.org/small-catechism/",note:"Primary confession"},{title:"Calvin, Institutes IV.19",url:"https://www.ccel.org/ccel/calvin/institutes.iv.xix.html",note:"Primary source"},{title:"Westminster Confession XV",url:"https://wts.edu/wcf",note:"Reformed confession"}]}} ,clash:["Sacramental absolution versus proclamation of forgiveness.","Priestly ministry of the keys versus pastoral ministry of the Word.","Satisfaction and penance versus repentance as fruit of faith.","The role of confession in assurance."],source:"Tertullian, On Repentance",sourceUrl:"https://www.newadvent.org/fathers/0312.htm"
    },
    {
      id:"scripture-tradition",name:"Scripture & Tradition",latin:"Scriptura et Traditio",short:"The relationship between the written apostolic Scriptures and the Church's received faith.",definition:"Christianity is a religion of revelation handed on through apostles, Scripture, preaching, worship, confession, and ecclesial memory. The dispute is not simply whether Christians should use tradition—every tradition does—but what authority Tradition has alongside Scripture and who possesses final interpretive authority.",scope:"The apostolic writings, Irenaeus, Vincent of Lérins, Augustine, medieval canon law and theology, the Reformation sola Scriptura, and Catholic and Orthodox conciliar theology shape the question.",treeUrl:"theological-tree.html?category=scripture-tradition",
      traditions:{
        catholic:{thesis:"Sacred Scripture and Sacred Tradition together constitute one deposit of faith, authentically interpreted by the Church's teaching office.",summary:"Catholic theology rejects both Scripture without Tradition and Tradition detached from Scripture. Scripture is inspired and uniquely authoritative as written revelation; apostolic Tradition transmits the same Gospel in the Church's worship, teaching, and life. The Magisterium does not stand above God's Word but serves it by authoritatively interpreting the deposit of faith. The canon itself is received through the Church's historical life.",sources:[{title:"Irenaeus, Against Heresies III.3",url:"https://www.newadvent.org/fathers/0103303.htm",note:"Apostolic succession and tradition"},{title:"Vatican II, Dei Verbum",url:"https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_en.html",note:"Primary magisterial source"},{title:"Catechism §§74–100",url:"https://www.vatican.va/archive/ENG0015/__P2H.HTM",note:"Synthesis"}]},
        orthodox:{thesis:"Scripture belongs within Holy Tradition: the same apostolic life that produced and preserved Scripture also provides the Church's liturgical, conciliar, and patristic interpretation.",summary:"Orthodox theology generally resists treating Scripture and Tradition as two rival sources. Scripture is the heart of Holy Tradition, while the liturgy, Fathers, Ecumenical Councils, iconography, and canonical life preserve the same apostolic faith. The Church does not stand over Scripture as an external magistrate; Scripture lives within the worshipping Church. The interpretive norm is therefore ecclesial, patristic, liturgical, and conciliar.",sources:[{title:"Irenaeus, Against Heresies III",url:"https://www.newadvent.org/fathers/0103303.htm",note:"Primary source"},{title:"Vincent of Lérins, Commonitory",url:"https://www.newadvent.org/fathers/3506.htm",note:"Patristic rule of faith"},{title:"John of Damascus, On the Orthodox Faith",url:"https://www.newadvent.org/fathers/3302.htm",note:"Primary source"}]},
        protestant:{thesis:"Scripture is the supreme and final norm of doctrine; tradition, councils, and teachers have genuine authority only insofar as they conform to Scripture.",summary:"Sola Scriptura does not mean that Christians should read the Bible without history, teachers, or creeds. Lutheran and Reformed churches receive ancient creeds and confessions because they judge them faithful summaries of Scripture. The decisive difference is that no ecclesial tradition is infallible in the same sense as inspired Scripture. The Reformers therefore appealed repeatedly to Fathers and councils while reserving final normative authority for the biblical canon.",sources:[{title:"Augsburg Confession Preface and I–IV",url:"https://bookofconcord.org/augsburg-confession/",note:"Primary confession"},{title:"Luther, Preface to Romans",url:"https://www.ccel.org/ccel/luther/nt_vol6.ii.html",note:"Primary source"},{title:"Westminster Confession I",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["Is Scripture the sole infallible norm, or one part of a larger apostolic deposit interpreted by the Church?","Who has final authority when Christians disagree about the meaning of Scripture?","Can the Church define doctrine beyond explicit biblical wording without adding to revelation?","How should the canon itself be justified historically and theologically?"],source:"Irenaeus, Against Heresies III.3",sourceUrl:"https://www.newadvent.org/fathers/0103303.htm"
    },
    {
      id:"predestination",name:"Predestination",latin:"Praedestinatio",short:"God's eternal purpose concerning the salvation of His creatures.",definition:"Predestination concerns God's eternal knowledge and purpose in salvation. All classical Christianity confesses divine providence, but it differs over election, reprobation, the role of foreknowledge, the extent of grace, and whether God's decree can be described as unconditional in the Reformed sense.",scope:"Paul, Augustine, Aquinas, the Reformation, the Synod of Orange, Calvin, Arminianism, and later Catholic and Orthodox discussions provide the principal history.",treeUrl:"theological-tree.html?category=predestination",
      traditions:{
        catholic:{thesis:"God eternally wills salvation and predestines the elect in grace, while His providence does not destroy human freedom or make God the author of sin.",summary:"Catholic theology strongly affirms God's initiative and foreknowledge while refusing to reduce human freedom to determinism. Augustine's mature writings are influential; Aquinas teaches predestination as an aspect of divine providence and places the cause of election in God rather than foreseen merit. Catholic theology does not define a simple universal mechanism for the relation between predestination and reprobation, and it rejects double-predestination understood as a symmetrical divine causation of good and evil.",sources:[{title:"Augustine, On the Predestination of the Saints",url:"https://www.newadvent.org/fathers/1512.htm",note:"Primary source"},{title:"Aquinas, ST I q.23",url:"texts/summa.html?part=prima&q=23&a=1",note:"Primary source"},{title:"Council of Orange II",url:"https://www.newadvent.org/fathers/1501.htm",note:"Grace and predestination context"}]},
        orthodox:{thesis:"God knows and wills the salvation of His creatures, but predestination is not a decree that negates freedom or makes God the cause of damnation.",summary:"Orthodox theology strongly affirms providence while resisting the later Calvinist formulation of unconditional election and double predestination. Salvation is offered genuinely to all, and human freedom remains meaningful within synergy. The tradition emphasizes God's foreknowledge, mercy, judgment, and the mystery of human response rather than constructing a comprehensive decree that explains every individual destiny. Theosis and communion remain the positive end of God's purpose.",sources:[{title:"John Chrysostom, Homilies on Romans",url:"https://www.newadvent.org/fathers/2102.htm",note:"Primary commentary"},{title:"John of Damascus, Exact Exposition",url:"https://www.newadvent.org/fathers/3304.htm",note:"Providence and freedom"},{title:"John Cassian, Conferences",url:"https://www.newadvent.org/fathers/3501.htm",note:"Grace and human response"}]},
        protestant:{thesis:"Reformed theology teaches unconditional election and effectual grace; Lutheran theology emphasizes election in Christ while avoiding speculative conclusions about a divine decree of damnation.",summary:"Calvinist theology makes predestination central to the doctrine of grace: God elects sinners according to His mercy, not foreseen merit, and effectually calls the elect to salvation. Reformed confessions explicitly teach election and reprobation while denying that God is the author of sin. Lutheran confessional theology also confesses election by grace in Christ but warns against speculation beyond the revealed Gospel and resists constructing a symmetrical decree of reprobation. Arminian and Wesleyan Protestants instead ground election conditionally in God's foreknowledge of faith and universal prevenient grace.",sources:[{title:"Calvin, Institutes III.21–24",url:"https://www.ccel.org/ccel/calvin/institutes.iii.xxi.html",note:"Primary Reformed source"},{title:"Westminster Confession III",url:"https://www.opc.org/wcf.html",note:"Reformed confession"},{title:"Formula of Concord, Election",url:"https://bookofconcord.org/formula-of-concord/",note:"Lutheran confession"}]}
      },clash:["Unconditional election versus election understood through foreknown faith.","Single predestination versus double predestination.","How can God's infallible providence coexist with genuinely free human acts?","Can the believer have assurance without turning election into speculation about a hidden decree?"],source:"Aquinas, Summa Theologiae I, q.23",sourceUrl:"texts/summa.html?part=prima&q=23&a=1"
    },
    {
      id:"faith-works",name:"Faith & Works",latin:"Fides et Opera",short:"The relationship between trusting faith, obedience, charity, and salvation.",definition:"The New Testament can say both that salvation is God's gift received through faith and that faith without works is dead. The historical question is therefore not whether Christians should do good works—every classical tradition says yes—but what works are, how they arise from grace, and whether they contribute to the believer's justification or only follow as its fruit.",scope:"Paul, James, Augustine, Aquinas, Luther, Melanchthon, Calvin, Trent, and the Reformed and Lutheran confessions provide the main sources.",treeUrl:"theological-tree.html?category=faith-works",
      traditions:{
        catholic:{thesis:"Faith is the beginning and root of justification, but living faith is inseparable from hope and charity; works performed in grace are truly pleasing to God and participate in the believer's growth in righteousness.",summary:"Catholic theology rejects earning initial grace by natural works. Yet once grace has been given, the believer's acts of charity are genuinely acts of the person transformed by grace. Trent therefore speaks of an increase of justification through cooperation with grace. Merit is derivative: God crowns His own gifts. James 2 is read not as contradicting Paul but as showing that faith which refuses obedience is not the living faith that unites the person to Christ.",sources:[{title:"Council of Trent, Session VI",url:"https://www.newadvent.org/cathen/15030c.htm",note:"Primary source"},{title:"Aquinas, ST I-II q.114",url:"texts/summa.html?part=prima-sec&q=114&a=1",note:"Merit and grace"},{title:"Augustine, On Faith and Works",url:"https://www.newadvent.org/fathers/1505.htm",note:"Patristic source"}]},
        orthodox:{thesis:"Faith is living trust in Christ expressed through repentance, sacramental participation, obedience, prayer, and love; works are the activity of a faith becoming life.",summary:"Orthodox theology is generally uncomfortable with treating faith and works as competing quantities. Faith is not merely intellectual assent but personal fidelity and communion. The believer's cooperation with grace is manifested in ascetic struggle, mercy, prayer, fasting, Eucharistic participation, and love. These works do not purchase God; they are the concrete expression of a person being healed and transformed. James and Paul are therefore read within one vision of living faith.",sources:[{title:"John Chrysostom, Homily on Matthew 25",url:"https://www.newadvent.org/fathers/2001.htm",note:"Works of mercy"},{title:"John Climacus, The Ladder of Divine Ascent",url:"https://archive.org/details/ladderofdivineascent0000john",note:"Ascetical source"},{title:"Maximus the Confessor, Selected Works",url:"https://archive.org/details/maximusconfessor0000maxi",note:"Secondary/free edition"}]},
        protestant:{thesis:"Faith alone justifies, but justifying faith is never alone: good works necessarily follow as the fruit of regeneration and union with Christ.",summary:"The Lutheran and Reformed distinction is between the ground or instrument of justification and the fruit of justification. The Augsburg Confession explicitly says that works are necessary because God commands them and because true faith produces them, but that they do not reconcile God or merit justification. Calvin similarly argues that faith receives Christ and His righteousness, while union with Christ necessarily produces sanctification. Thus 'faith alone' is not a defense of inactive or merely verbal belief; it excludes works as the ground of the sinner's acceptance.",sources:[{title:"Augsburg Confession IV, VI, XX",url:"https://bookofconcord.org/augsburg-confession/",note:"Primary Lutheran confession"},{title:"Formula of Concord III–IV",url:"https://bookofconcord.org/formula-of-concord/",note:"Faith and works"},{title:"Calvin, Institutes III.16–18",url:"https://www.ccel.org/ccel/calvin/institutes.iii.xvi.html",note:"Primary Reformed source"},{title:"Westminster Confession XVI",url:"https://www.opc.org/wcf.html",note:"Reformed confession"}]}
      },clash:["Is faith alone the instrument of justification, or is faith completed by charity within justification?","Can works performed in grace increase the believer's righteousness before God?","How should Paul and James be harmonized?","Does excluding works from justification risk antinomianism, or does including them risk undermining grace?"],source:"Augsburg Confession, Articles IV and XX",sourceUrl:"https://bookofconcord.org/augsburg-confession/"
    }
  ];

  /* The UI historically uses one Protestant card. Its summary intentionally
     distinguishes Lutheran and Reformed positions rather than flattening them. */
  const grid = document.getElementById("concept-grid");
  const detail = document.getElementById("concept-detail");
  window.CONCEPTS = concepts;

  function escapeHtml(value) {
    return String(value == null ? "" : value).replace(/[&<>\"]/g, function (character) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[character];
    });
  }

  function renderDetail(concept) {
    if (!detail) return;
    let html =
      '<div class="concept-detail-rule"></div>' +
      '<span class="concept-detail-kicker">' + escapeHtml(concept.latin) + "</span>" +
      "<h2>" + escapeHtml(concept.name) + "</h2>" +
      '<p class="concept-definition">' + escapeHtml(concept.definition) + "</p>" +
      '<p class="concept-scope">' + escapeHtml(concept.scope) + "</p>";

    if (concept.traditions) {
      html += '<div class="concept-traditions">';
      ["catholic", "orthodox", "protestant"].forEach(function (key) {
        const t = concept.traditions[key];
        if (!t) return;
        const label = key === "catholic" ? "Catholic" : key === "orthodox" ? "Eastern Orthodox" : "Protestant";
        html += '<section class="concept-tradition-card trad-' + key + '">' +
          '<header><span class="trad-badge">' + label + "</span></header>" +
          '<p class="trad-thesis">' + escapeHtml(t.thesis) + "</p>" +
          "<p>" + escapeHtml(t.summary) + "</p>";
        if (t.sources && t.sources.length) {
          html += '<ul class="trad-sources">';
          t.sources.forEach(function (src) {
            html += '<li><a href="' + escapeHtml(src.url) + '" target="_blank" rel="noopener">' +
              escapeHtml(src.title) + '</a>' +
              (src.note ? ' <span class="src-note">— ' + escapeHtml(src.note) + "</span>" : "") +
              "</li>";
          });
          html += '</ul>';
        }
        html += '</section>';
      });
      html += '</div>';
    }

    if (concept.clash && concept.clash.length) {
      html += '<div class="concept-clash"><h3>Where the traditions clash</h3>' +
        '<p class="clash-intro">These are the questions on which the traditions genuinely diverge.</p><ul>' +
        concept.clash.map(function (c) { return '<li>' + escapeHtml(c) + '</li>'; }).join("") +
        '</ul></div>';
    }

    html += '<div class="concept-detail-actions">' +
      '<a class="btn btn-primary" href="concept.html?id=' + encodeURIComponent(concept.id) + '">Open full entry</a>' +
      '<a class="btn btn-primary" href="' + escapeHtml(concept.treeUrl || "theological-tree.html") + '">Theological Tree</a>' +
      '<a class="concept-source" href="' + escapeHtml(concept.sourceUrl || "#") + '" target="_blank" rel="noopener">Primary reference: ' +
      escapeHtml(concept.source || "Source") + '</a></div>';

    detail.innerHTML = html;
    detail.classList.add("is-visible");
  }

  if (grid) {
    concepts.forEach(function (concept, index) {
      const card = document.createElement("a");
      card.href = "concept.html?id=" + encodeURIComponent(concept.id);
      card.className = "concept-card";
      card.style.setProperty("--card-order", String(index));
      card.setAttribute("aria-label", "Read about " + concept.name);
      card.dataset.id = concept.id;
      card.innerHTML = '<span class="concept-card-number">' + String(index + 1).padStart(2, "0") + '</span>' +
        '<span class="concept-card-latin">' + escapeHtml(concept.latin) + '</span>' +
        '<span class="concept-card-title">' + escapeHtml(concept.name) + '</span>' +
        '<span class="concept-card-summary">' + escapeHtml(concept.short) + '</span>';
      card.addEventListener("click", function (e) {
        if (!detail) return;
        e.preventDefault();
        document.querySelectorAll(".concept-card").forEach(function (c) { c.classList.remove("is-selected"); });
        card.classList.add("is-selected");
        renderDetail(concept);
        detail.scrollIntoView({ behavior: "smooth", block: "nearest" });
        history.replaceState(null, "", "concepts.html?concept=" + encodeURIComponent(concept.id));
      });
      grid.appendChild(card);
    });

    if (detail) {
      const initialId = new URLSearchParams(window.location.search).get("concept") || "grace";
      const initial = concepts.find(function (c) { return c.id === initialId; }) || concepts[0];
      const initialCard = Array.from(document.querySelectorAll(".concept-card")).find(function (c) { return c.dataset.id === initial.id; });
      if (initialCard) initialCard.classList.add("is-selected");
      if (initial) renderDetail(initial);
    }
  }
})();
